# Generated by Django 5.2.3 on 2025-07-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interest_notes',
            field=models.TextField(blank=True, default='', verbose_name="User's Stated Interests"),
        ),
    ]
